services:
  # Cron job to run the scraper once daily at 16:00 UTC
  - type: cron
    name: ads-africa-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper.py
    plan: free
    schedule: "0 16 * * *"  # Run daily at 16:00 UTC
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SUPABASE_URL
        sync: false  # User must set this in Render dashboard
      - key: SUPABASE_KEY
        sync: false  # User must set this in Render dashboard
      - key: BUCKET_NAME
        value: screenshots
      - key: TABLE_NAME
        value: listings
      - key: BASE_URL
        value: https://www.adsafrica.co.za/category/65
      - key: BATCH_SIZE
        value: 10
      - key: MAX_PAGES
        value: 150
      - key: MAX_WORKERS
        value: 5
      - key: SCREENSHOT_WAIT_TIME
        value: 3
      - key: MAX_RETRIES
        value: 3
      - key: TEMP_DIR
        value: /tmp
