name: Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install Chrome
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get -y install google-chrome-stable

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade --force-reinstall -r requirements.txt

      # Step 5: Run scraper script
      - name: Run scraper
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          BUCKET_NAME: screenshots
          TABLE_NAME: listings
          BASE_URL: https://www.adsafrica.co.za/category/65
          MAX_PAGES: 150
          MAX_WORKERS: 5
          HTTP_PROXY: ""
          HTTPS_PROXY: ""
          NO_PROXY: "*"
        run: |
          python scraper.py || true  # Avoid premature failure to capture logs

      # Step 6: Upload scraper.log as artifact
      - name: Upload scraper log
        if: always() # Always upload log, regardless of job status
        uses: actions/upload-artifact@v4
        with:
          name: scraper-log
          path: scraper.log

      # ✅ Step 7: Upload summary.txt as artifact (NEW)
      - name: Upload summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: summary
          path: summary.txt

      # Step 8: Optional Email Notification (GitHub built-in)
      # No changes needed, GitHub sends email notifications automatically for failed runs.
